language: rust

# Caching based off of https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
    - /home/travis/.rustup

before_cache:
  - rm -rf /home/travis/.cargo/registry

jobs:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "deb http://archive.ubuntu.com/ubuntu/ eoan universe" # for libsofthsm2 2.5.0
          packages:
            - libsofthsm2
      env: PKCS11_SOFTHSM2_MODULE=/usr/lib/softhsm/libsofthsm2.so RUST_BACKTRACE=1
      before_script:
        - sudo usermod -a -G softhsm $USER # So we have enough permissions to make the tokens directory
    - os: osx
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew
      env: HOMEBREW_NO_INSTALL_CLEANUP=1
      addons:
        homebrew:
          packages:
          - softhsm

script:
  - cargo build
  - cargo test -- --nocapture --test-threads 1