language: rust

# Caching based off of https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
    - /home/travis/.rustup

before_cache:
  - rm -rf /home/travis/.cargo/registry

jobs:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libsofthsm2
      script: # See https://docs.travis-ci.com/user/reference/trusty/#group-membership for why we need to do this
        - sudo usermod -a -G softhsm $USER # So we have enough permissions to make the tokens directory
        - sudo -E su $USER -c 'export PATH=${TRAVIS_HOME}/.cargo/bin:$PATH && export PKCS11_SOFTHSM2_MODULE=/usr/lib/softhsm/libsofthsm2.so && cargo build && cargo test' # So we have the group added
    - os: osx
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew
      env: HOMEBREW_NO_INSTALL_CLEANUP=1
      addons:
        homebrew:
          packages:
          - softhsm
      script:
        - cargo build
        - cargo test