language: rust
dist: bionic

os: linux

# Caching based off of https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
    - /home/travis/.rustup

before_cache:
  - rm -rf /home/travis/.cargo/registry

addons:
  apt:
    sources:
      - sourceline: "deb http://archive.ubuntu.com/ubuntu/ eoan universe" # for libsofthsm2 2.5.0
    packages:
      - libsofthsm2

env:
  global:
    - PKCS11_SOFTHSM2_MODULE: /usr/lib/softhsm/libsofthsm2.so
    - RUST_BACKTRACE: 1

script:
  - apt-cache policy libsofthsm2 softhsm2-common softhsm2
  - dpkg -L libsofthsm2
  - ls -l /usr/lib/softhsm/libsofthsm2.so
  - cargo build
  - cargo test -- --nocapture --test-threads 1