language: rust
dist: bionic

# Caching based off of https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
    - /home/travis/.rustup

before_cache:
  - rm -rf /home/travis/.cargo/registry

addons:
  apt:
    packages:
      - libsofthsm2

env:
  global:
    - PKCS11_SOFTHSM2_MODULE: /usr/lib/softhsm/libsofthsm2.so

script:
  - cargo build
  - cargo test
