name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      PKCS11_SOFTHSM2_MODULE: /usr/lib/softhsm/libsofthsm2.so
    steps:
    - uses: actions/checkout@v2
    - name: SoftHSM installation
      run: |
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ disco universe"
        sudo apt-get install -f libsofthsm2
        export ORIG_USER="$USER"
        sudo usermod -a -G root,softhsm $ORIG_USER
        cat /etc/softhsm/softhsm2.conf
    - name: build
      run: cargo build --verbose
    - name: test
      run: groups && cargo test --verbose
