name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      PKCS11_SOFTHSM2_MODULE: /usr/lib/softhsm/libsofthsm2.so
    steps:
    - uses: actions/checkout@v2
    - name: SoftHSM installation
      run: sudo apt-get install -f libsofthsm2
    - name: build
      run: cargo build --verbose
    - name: test
      run: cargo test --verbose
