name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      PKCS11_SOFTHSM2_MODULE: /usr/lib/softhsm/libsofthsm2.so
    steps:
    - uses: actions/checkout@v2
    - name: tarpaulin installation
      run: |
        sudo apt-get install -f libssl-dev
        cargo install cargo-tarpaulin
    - name: SoftHSM installation
      run: |
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ disco universe"
        sudo apt-get install -f libsofthsm2
        sudo usermod -a -G softhsm $USER
    - name: build
      run: cargo build --verbose
    - name: test
      run: |
        sg softhsm -c \
          'cargo test --verbose'
    - name: coverage
      run: |
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
