name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: macos-latest
    env:
      PKCS11_SOFTHSM2_MODULE: "/usr/local/lib/softhsm/libsofthsm2.so"
    steps:
    - uses: actions/checkout@v2
    - name: SoftHSM installation
      run: brew install -f softhsm
    - name: build
      run: cargo build --verbose
    - name: test
      run: cargo test --verbose
    # TODO: these are currently not installed in the toolchain
    #       of the GitHub action runners for macOS
    #       reenable them again once they are, or install them
    #- name: rustfmt
    #  run: cargo fmt -- --check
    #- name: clippy 
    #  run: cargo clippy --all-targets --all-features -- -D warnings
